CREATE TABLE IF NOT EXISTS trades (
  seq_id INT AUTO_INCREMENT PRIMARY KEY,
  id VARCHAR(12) GENERATED ALWAYS AS (CONCAT('TRD-', LPAD(seq_id, 6, '0'))) STORED UNIQUE,
  symbol VARCHAR(16) NOT NULL,
  quantity DECIMAL(18, 4) NOT NULL,
  price DECIMAL(18, 4) NOT NULL,
  side ENUM('BUY', 'SELL') NOT NULL,
  trader NVARCHAR(100) NOT NULL,
  trade_date DATE NOT NULL,
  status ENUM('ACTIVE', 'CANCELLED') NOT NULL DEFAULT 'ACTIVE'
);
